// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRHfv_Q7tGwWFcGiuesM9Mn73fJNlUNc',
    appId: '1:327518543252:web:bae3381c6397403248c381',
    messagingSenderId: '327518543252',
    projectId: 'medoc-477e8',
    authDomain: 'medoc-477e8.firebaseapp.com',
    storageBucket: 'medoc-477e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhiq6lbFPqBnjh9irygR041Nw8ZM-yNnI',
    appId: '1:327518543252:android:b18911d524970ad248c381',
    messagingSenderId: '327518543252',
    projectId: 'medoc-477e8',
    storageBucket: 'medoc-477e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAYk3Ov0pSI3rOE8VbXYL_gHxWvFdvHhE',
    appId: '1:327518543252:ios:13dcfd4251e4cb7b48c381',
    messagingSenderId: '327518543252',
    projectId: 'medoc-477e8',
    storageBucket: 'medoc-477e8.appspot.com',
    iosClientId: '327518543252-5i6fm277scsfr377mubid8vu9m2kidaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.medocPatientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAYk3Ov0pSI3rOE8VbXYL_gHxWvFdvHhE',
    appId: '1:327518543252:ios:bb143ab32f89c56e48c381',
    messagingSenderId: '327518543252',
    projectId: 'medoc-477e8',
    storageBucket: 'medoc-477e8.appspot.com',
    iosClientId: '327518543252-0eca3piq7p6ap5ouk1t81nucdfbmlggt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medocPatientApp.RunnerTests',
  );
}
